#
# SSH Daemon Service
#
# Images를 선택
FROM     ubuntu:14.04

MAINTAINER heewoo <heewoo7139@gmail.com>

# Keep upstart from complaining
RUN dpkg-divert --local --rename --add /sbin/initctl
RUN ln -sf /bin/true /sbin/initctl


# Let the conatiner know that there is no tty
ENV DEBIAN_FRONTEND noninteractive


# Basic & oracle java8
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:webupd8team/java -y && \
    apt-get update && \
    echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get install -y oracle-java8-installer && \
    apt-get install -y ant && \
    apt-get clean


# 기존 미러 서버를 한국 서버로 변경
RUN sed -i 's/archive.ubuntu.com/ftp.neowiz.com/g' /etc/apt/sources.list

# 최신버전으로 업데이트 후 SSH 및 필요 패키지 설치
RUN apt-get update ; apt-get install -y openssh-server aptitude net-tools curl

# SSH 관련 설정
RUN mkdir /var/run/sshd
RUN sed  -i "/^[^#]*UsePAM/ s/.*/#&/"  /etc/ssh/sshd_config
RUN echo "UsePAM no" >> /etc/ssh/sshd_config

# Root 비밀번호 설정
RUN echo 'root:root' | chpasswd

#host file
ADD ./hosts /etc/hosts
ADD ./authorized_keys /root/.ssh/authorized_keys

#nutch copy
COPY ./nutch /usr/lib/nutch